### ISSUE TITLE
USER STORY: Submit gig photo

### ISSUE THREAD

**Issue by mjjstockman** [mjjstockman/setlist-sharer-final#12]
As a **Site User** I can **submit a photo for a gig** so that **it can be added to the site**

# Acceptance Criteria

 - I can choose a gig without a photo and upload a photo
 - This can be submitted for approval

# Tasks

- [ ] Create addphoto app
- [ ] Create /addphoto, template and view
- [ ] Create form
- [ ] Manually test submitting a photo
