### ISSUE TITLE
USER STORY: View numbers agreeing / disagreeing with a setlist

### ISSUE THREAD

**Issue by mjjstockman** [mjjstockman/setlist-sharer-final#17]
As a **Site User** I can **see if how many users have agreed or disagreed with a setlist** so that **I can gauge its accuracy**

# Acceptance Criteria

 - The number of users agreeing and disagreeing with a setlist are shown on the site

# Tasks

- [ ] Add the number of users agreeing and disagreeing with a setlist to the home page
- [ ] Add the number of users agreeing and disagreeing with a setlist detail page
- [ ] Manually test the numbers agreeing/disagreeing
