### ISSUE TITLE
USER STORY: Add songs for users to add to setlists

### ISSUE THREAD

**Issue by mjjstockman** [mjjstockman/setlist-sharer-final#20]
As a **Site Admin** I can **create a list of the bands songs** so that **users can choose from these songs and ensure song titles are correct**

# Acceptance Criteria

 - I can add songs through the admin 
 - The songs are shown for the user to select when creating a setlist

# Tasks

- [ ] Create Song model
- [ ] Create Release model
- [ ] Add User model
- [ ] Create Gig model
- [ ] Create Venue model
- [ ] Create Photo model
