### ISSUE TITLE
USER STORY: Initial set up

### ISSUE THREAD

**Issue by mjjstockman** [mjjstockman/setlist-sharer-final#22]
As a **Site Admin** I can **populate the database with gig and song data** so that **users can access the data needed for the site**

# Acceptance Criteria

 - I can add venue, gig, song and release data

# Tasks

- [ ] Create Venue model
- [ ] Create Gig model
- [ ] Create Song model
- [ ] Create Release model
- [ ] Create Setlist model
- [ ] Add User model
