### ISSUE TITLE
USER STORY: View login page

### ISSUE THREAD

**Issue by mjjstockman** [mjjstockman/setlist-sharer-final#3]
As a **Site User** I can **see the login page** so that **I can log in and use all site features**

# Acceptance Criteria

 - Clicking on the login link takes you to the log in page
 - Filling in the form with correct data logs the user in
 - Once logged in the user is taken to the home page

# Tasks

- [ ] Create test
- [ ] Install and set up allauth
- [ ] Add base template to allauth templates
- [ ] Redirect to the home page
- [ ] Add HTML and CSS
