### ISSUE TITLE
USER STORY: View sign up

### ISSUE THREAD

**Issue by mjjstockman** [mjjstockman/setlist-sharer-final#4]
As a **Site User** I can **see the sign page** so that **I can sign up to the site**

# Acceptance Criteria

 - Clicking on the sign up link takes me to the sign up page
 - Filling in the form with correct data signs the me up to the site
 - Once signed up I am taken to the log in page

# Tasks

- [ ] Create test
- [ ] Install and set up allauth
- [ ] Redirect to the login page
- [ ] Add HTML and CSS
